on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Retrieve the secret and decode it to a file
      env:
        DEPLOY_KEY_BASE64: ${{ secrets.SSH_DEPLOY_KEY_RSA}}
      run: |
        mkdir -p ./secrets/
        echo $DEPLOY_KEY_BASE64 | base64 --decode > ./secrets/id_rsa
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32s2
        path: './'
        command: |
          echo "Add github.com to known hosts"
          mkdir -p ~/.ssh; chmod go-rwx ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          cp ./secrets/id_rsa ~/.ssh/
          chmod 400 ~/.ssh/id_rsa
          ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
          ssh -vT git@github.com
          sleep 3
          idf.py build
    - name: Rename artifact
      run: |
        ls -lah 
        cp ./build/main.bin firmware.bin
    - name: Archive Firmware Files
      uses: actions/upload-artifact@v3
      with: 
        name: firmware
        path: "firmware.bin"

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Firmware Files
      uses: actions/download-artifact@v2
      with:
        path: release
    - name: Release Firmware
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/') 
      with:
        artifacts: release/*/*.bin
        generateReleaseNotes: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}